#!/bin/bash
source helper

docker build --pull --target dev --tag "${IMAGE}:dev" $@ .

docker run --rm -p 8000:8000 \
  -e KUBECONFIG=/kubeconfig \
  -v /mnt/ceph/docker-kubernetes-master/vault-data/cluster-admin-kubeconfig.yml:/kubeconfig \
  -v `pwd`:/go/src/github.com/mingfang/terraform-provider-k8s \
  -v `pwd`/../terraform-k8s-modules:/go/src/github.com/mingfang/terraform-provider-k8s/modules \
  -v `pwd`/gnupg:/root/.gnupg \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -w /go/src/github.com/mingfang/terraform-provider-k8s \
  -it "${IMAGE}:dev" bash
