#!/bin/bash

for dir in ${1:-archetypes modules solutions examples test}; do
  grep -r '//GENERATE DYNAMIC' $dir|sed 's|://|//|'|awk -F'//' '{printf "%s %s \"%s\" \"%s\"\n", $1, $3, $4, $5}'|xargs -n 4 -r sh -cx 'generator -dynamic -count "$2" -lifecycle "$3" $1 > $0'
done